#!/bin/bash

cd ./form_bin

array_pdf=( * )
array_full_pdf=( * )

num_of_pdf=$(echo ${#array_pdf[@]})
total=$(echo ${num_of_pdf})



iter=0
for i in "${array_pdf[@]}"
do
	name=$(echo $i | cut -f 1 -d '.')
	array_pdf[$iter]=$name
	iter=$((iter+1))
done

#echo "${array_pdf[@]}"

cd ../form_bin

iter=0
for i in "${array_pdf[@]}"
do
	convert -colorspace sRGB -density 300 ${array_full_pdf[$iter]} -background white -alpha background -alpha remove -colorspace RGB -resize %200 ${i}.png
	iter=$((iter+1))
done


mv *.png ../png_bin

cd ..

for file in png_bin/*.png; do
	[ -e "$file" ] || continue
	./AlphaState ./${file}
done
