#!/bin/bash

chmod 777 AlphaState.cpp
chmod 777 SigLoc_Struct.h
chmod 777 OCR_SigLoc.cpp
chmod 777 ConvNet.cpp

g++ AlphaState.cpp -o AlphaState `pkg-config opencv --cflags --libs` -llept -ltesseract

cd ./form_bin

array_pdf=( * )
array_full_pdf=( * )

num_of_pdf=$(echo ${#array_pdf[@]})
total=$(echo ${num_of_pdf})


#Prepare pdf names for usage
iter=0
for i in "${array_pdf[@]}"
do
	name=$(echo $i | cut -f 1 -d '.')
	array_pdf[$iter]=$name
	iter=$((iter+1))
done

cd ../form_bin

#Look through all pdf's present in form_bin and pass them through ImageMagick
iter=0
for i in "${array_pdf[@]}"
do
	convert -colorspace sRGB -density 300 ${array_full_pdf[$iter]} -background white -alpha background -alpha remove -colorspace RGB -resize %200 ${i}.png
	iter=$((iter+1))
done

#Send all single page images into png_bin folder for next stage
mv *.png ../png_bin

cd ..

#Loop through all single page png's and submit through to remainder of program
for file in png_bin/*.png; do
	[ -e "$file" ] || continue
	./AlphaState ./${file}
done

#Clean up directories for png_bing and images
cd png_bin
rm -f *.png

cd ..

cd image
rm -f *.png
